"""auto update

Revision ID: 664391815d3f
Revises: c9d7b7efd640
Create Date: 2026-09-17 23:54:59.986524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664391815d3f'
down_revision: Union[str, Sequence[str], None] = 'c9d7b7efd640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_history', sa.Column('app_title', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('category', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('kind', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('html_code', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('plan_summary', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('model', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('generation_history', sa.Column('instruction', sa.String(), nullable=True))
    op.alter_column('generation_history', 'template_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generation_history', 'template_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('generation_history', 'instruction')
    op.drop_column('generation_history', 'version')
    op.drop_column('generation_history', 'model')
    op.drop_column('generation_history', 'plan_summary')
    op.drop_column('generation_history', 'html_code')
    op.drop_column('generation_history', 'kind')
    op.drop_column('generation_history', 'category')
    op.drop_column('generation_history', 'app_title')
    # ### end Alembic commands ###