"""auto update

Revision ID: c9d7b7efd640
Revises: 8df513695122
Create Date: 2026-09-17 23:12:55.450543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d7b7efd640'
down_revision: Union[str, Sequence[str], None] = '8df513695122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_history_user_id'), table_name='generation_history')
    op.drop_column('generation_history', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_history', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_generation_history_user_id'), 'generation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###